### ISSUE TITLE
Bug: Unclean checking leads to errors

### ISSUE THREAD

**Issue by flosse** [devashishdxt/idb#12]
In case the `JsValue` is `0` a `None` would be returned although it might be e.g. a valid key.

https://github.com/devashishdxt/idb/blob/750d6d3a3e4c2e0a0e0c821c853e5e8b1db8d0c0/idb/src/utils.rs#L93-L98

We should use the advantages of Rust instead of copying the bad JS behavior (otherwise we could write everything in JS :stuck_out_tongue_winking_eye:  )

So my my suggestion would be to remove that check completely and also return `T` instead of `Option<T>` because you require 

https://github.com/devashishdxt/idb/blob/750d6d3a3e4c2e0a0e0c821c853e5e8b1db8d0c0/idb/src/utils.rs#L86

anyway. And silently dropping data is a bad idea in general. Instead the caller (that has knowledge about the context) should decide how to handle the value.

What do you think?

**Comment by devashishdxt** [comment]
Hi. I've created this PR: #14 which resolves the issue without introducing breaking API changes.

**Comment by devashishdxt** [comment]
Release a new version on crates.io with the fix.
