### ISSUE TITLE
idb_sys: expose the Database from the VersionChangeEvent

### ISSUE THREAD

**Issue by Ekleog** [devashishdxt/idb#15]
Hey! Considering #7, I'm trying to use `idb-sys` for my database handling.

I'm just curious, is there any reason why this code is in idb, and not exposed straight from the VersionChangeEvent of idb-sys?
https://github.com/devashishdxt/idb/blob/45762491f4d9112d7ce2604e9c0349c217540e9c/idb/src/database.rs#L129-L132

Anyway, it looks like idb-sys will be a great way for me to have both the reliability I'm looking for, but also some relative ease-of-use compared to web-sys and its untyped API. So, thank you! :D

**Comment by Ekleog** [comment]
Incidentally, it'd be great if the `on_success` / `on_error` callbacks could return an `idb_sys::Event` type, that'd similarly provide for easy access to the underlying database :)

**Comment by devashishdxt** [comment]
Fixed in #19.
