### ISSUE TITLE
Add derive macros for store serialization/deserialization in IDB

### ISSUE THREAD

**Issue by LucaCappelletti94** [devashishdxt/idb#28]
Hi,

Currently, when working with structs in IDB, it's necessary to manually define the store and write repetitive code for inserting and extracting objects. This functionality can be efficiently automated using a derive macro, reducing boilerplate and potential errors.

If I haven’t overlooked any key technical constraints that would make such macros unfeasible, I’d be happy to contribute by implementing this feature. Please let me know your thoughts before I proceed, to ensure that this aligns with the project's direction.

Looking forward to your feedback!

**Comment by devashishdxt** [comment]
I've already attempted to implement derive macros in `deli` crate. Haven't updated it in some time as there aren't many users for it. You can take a look at it

**Comment by LucaCappelletti94** [comment]
Ok, we make chat it over there.
